bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users do
  resource :relationships, only: [:create, :destroy] 
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :following, :followers
    end  
  end
  
  
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where(book: word)
    elsif search == "partail_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end  
  end
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id 
    if @book.save
      flash[:notice] = 'successfully'
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end  
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end 

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new = Book.new
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end  
  end 
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'successfully'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end 
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end  
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/views/books/_list.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <table class="table">
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>  
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <td>follows</td>
      <td><%= link_to user.followings.count, user_followings_path(user) %></td>
    </tr>  
    <tr>
      <td>followers</td>
      <td><%= link_to user.followers.count, user_followers_path(user) %></td>  
    </tr>
  </table>
       
  <%= link_to "", edit_user_path(user),class:"btn btn-secondary btn-block fas fa-user-cog edit_user_id" %>
        
<h2>New book</h2>
<%= form_with model:book, url:'/books', local:true do |f| %>

<h4>title</h4>
<%= f.text_field :title %>

<h4>body</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Create Book', class: "btn btn-success btn-sm" %>

<% end %>    

bookers2/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>   

<div class="container">
  <div class="row">
    <div class="mx-auto">  
      <h1>Editing Book</h1>
      <%= form_with model:@book, url:"/books/#{@book.id}", local: true do |f| %>

      <h4>title</h4>
      <%= f.text_field :title %>

      <h4>body</h4>
      <%= f.text_area :body %>

      <br><%= f.submit 'Update Book', class: "btn btn-success btn-sm" %>

      <% end %> 

      <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      <!--<a class="book_id" href="/books/id">Show</a> | <a class="books" href="/books"></a>-->
    </div>
  </div>
</div>  

bookers2/app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>  

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "books/list",book:@book,user:@user %>
    </div>
      
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
          
            <table class="table">
              <thead>
                <tr>
                  <td></td>
                  <td>title</td>
                  <td>body</td>
                </tr>
              </thead>
          
          　 　<tbody>
          　 　 <% @books.each do |book| %> 
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                  </td>
                    <% end %>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                  <td>
                    <%= render "favorites/favorite-btn", book: book %>
                  </td>
                  <td><p><%= link_to "コメント数#{book.book_comments.count} ", book_path(book.id) %></p>
                </tr>
                <% end %> 
              </tbody> 
            </table>
      </div>
  </div>
</div>

bookers2/app/views/books/new.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <img class="attachment user profile_image fallback" src="no_image.jpg">
        <table>
          <tr>
            <td>name</td>
          </tr>  
          <tr>
            <td>introduction</td>
          </tr>    
        </table>
        <div class="row">
          <a class="btn btn-secondary rtn-block fas fa-user-cog edit_user_id" ></a>    
        </div>
      </div>    
    </div>
  </div>    
</main>

<h1>New Book</h1>
<%= form_with model:@book, url:'/books', local:true do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>

   <h4>body</h4>
  <%= f.text_area :body %>

  <br><%= f.submit 'Create Book' %></>

<% end %>

bookers2/app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "books/list",book:@new,user:@user %>
    </div>
          
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>      
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@book.user) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
                  <div><%= @book.user.name %></div>
                  <% end %>
                </td>  
                <td><%= link_to @book.title %></td>
                <td><%= @book.body %></td>
                <td>
                  <%= render "favorites/favorite-btn", book: @book %>
                </td>    
                <td><p>コメント数：<%= @book.book_comments.count %></p></td>
                  <% if @book.user == current_user %>
                <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success btn-sm" %></td>
                <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-danger btn-sm" %></td>
                  <% end %>
              </tr>
                <td>
                  <%= render "book_comments/comment", book: @book %>
                </td>
              
              
            </tbody>  
          </table>
  
              <div class="new-comment">
                <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
                <%= f.text_area :comment, size:"90x5",placeholder: "コメントをここに" %>
                <br><%= f.submit "送信" %>
                <% end %>
              </div>
      </div>
  </div>  
</div>
          
          
  
          





  